language: python
python:
  - 3.5
  - 3.6
services:
  - postgresql
addons:
  postgresql: '9.6'
env:
  - DJANGO=django==2.2.5 DRF=3.9.0 DATABASE_URL=postgres://postgres@localhost/test
sudo: false
install:
  - pip install $DJANGO && pip install sphinx coveralls djangorestframework==$DRF
  - if [[ "$DATABASE_URL" == postgres:* ]]; then pip install psycopg2; fi
  - python setup.py -q install
before_script:
  - psql -c 'create database test;' -U postgres
script:
  coverage run --source=hvad --omit='hvad/test*' runtests.py
after_success:
  if [[ $COVERALLS_REPO_TOKEN ]]; then coveralls; fi
